# Generated by Django 3.2.8 on 2021-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=500, null=True)),
                ('generated_url', models.URLField(max_length=100, null=True)),
            ],
        ),
    ]
